### ISSUE TITLE
星哥，现在binding.node的48出来了

### ISSUE THREAD

**Issue by richard-chen-1985** [wshxbqq/jdf-sass#1]
如题，是时候升级了，我在osx中用node v6已经不能用jdf了

**Comment by wshxbqq** [comment]
现在是有 48的啊  
而且我试了一下 6.x的node在osx上可以用呀 
![Uploading QQ20160806-1.png…]()

**Comment by wshxbqq** [comment]
![1](https://cloud.githubusercontent.com/assets/1445609/17454838/aaf8dc50-5bd7-11e6-82c6-17133982698d.png)
现在是有 48的啊  
而且我试了一下 6.x的node在osx上可以用呀 . 

不太建议用6.x的 node 太新了,很多包都不兼容.

**Comment by richard-chen-1985** [comment]
你看你的install.js，只到47的，我也是偶然发现，因为我有些项目交接了，不知道的同事就会直接装最新版的node，然后去装jdf。现在安装node-sass其实也会先下载二进制文件，但不知道为啥居然老是下不下来，真是悲剧。

**Comment by wshxbqq** [comment]
哦 明白了, 我只在npm上发布了新的版本, 可能是忘记同步到github上了.

使用npm install -g jdf 会自动使用新的 sass包,
